#pragma once

#include "game_types.h"

#include <algorithm>
#include <cmath>
#include <limits>
#include <random>
#include <string>

inline constexpr int kIronAtomicNumber = 26;

struct GameState {
  double energy = 0.0;
  double protons = 0.0;
  double neutrons = 0.0;
  double electrons = 0.0;
  double star_dust = 0.0;

  double click_power = 1.0;
  double crit_chance = 0.0;
  double crit_multiplier = 2.0;
  double auto_eps = 0.0;
  double auto_click_mult = 1.0;
  // Multiplier for passive eV/s generated by held isotopes.
  double isotope_eps_mult = 1.0;

  // Energy cost to materialize one particle.
  double price_proton = 10.0;
  double price_neutron = 12.0;
  double price_electron = 5.0;

  StarType star_type = StarType::BrownDwarf;
  CraftBatch craft_batch = CraftBatch::x1;  // Lab nucleus/atom craft
  CraftBatch buy_batch = CraftBatch::x1;    // p/n/e materialize

  std::vector<Element> elements;
  std::vector<UpgradeDef> upgrades;

  std::mt19937 rng{std::random_device{}()};

  void InitNewGame() {
    energy = 0.0;
    protons = 0.0;
    neutrons = 0.0;
    electrons = 0.0;
    star_dust = 0.0;
    click_power = 1.0;
    crit_chance = 0.0;
    crit_multiplier = 2.0;
    auto_eps = 0.0;
    auto_click_mult = 1.0;
    isotope_eps_mult = 1.0;
    star_type = StarType::BrownDwarf;
    craft_batch = CraftBatch::x1;
    buy_batch = CraftBatch::x1;
    elements = CreateDefaultElements();
    upgrades = CreateDefaultUpgrades();
    UnlockElementsForStar();
  }

  static std::vector<Element> CreateDefaultElements() {
    return {
        Element{"Hydrogen", L"Hydrogen", 1, 1, 1, 1, 8.0, 0, 0, 0, true, false},
        Element{"Helium", L"Helium", 2, 2, 2, 2, 40.0, 0, 0, 0, true, false},
        Element{"Carbon", L"Carbon", 6, 6, 6, 6, 220.0, 0, 0, 0, false, false},
        Element{"Oxygen", L"Oxygen", 8, 8, 8, 8, 480.0, 0, 0, 0, false, false},
        Element{"Silicon", L"Silicon", 14, 14, 14, 14, 1800.0, 0, 0, 0, false,
                false},
        Element{"Iron", L"Iron", 26, 26, 30, 26, 12000.0, 0, 0, 0, false, false},
        // Mid ladder toward Gold (Neutron Star).
        Element{"Nickel", L"Nickel", 28, 28, 30, 28, 20000.0, 0, 0, 0, false,
                false},
        Element{"Silver", L"Silver", 47, 47, 60, 47, 55000.0, 0, 0, 0, false,
                false},
        Element{"Xenon", L"Xenon", 54, 54, 78, 54, 110000.0, 0, 0, 0, false,
                false},
        Element{"Gold", L"Gold", 79, 79, 118, 79, 250000.0, 0, 0, 0, false,
                false},
    };
  }

  static std::vector<UpgradeDef> CreateDefaultUpgrades() {
    std::vector<UpgradeDef> list;

    // Particle tree (display order: electron → proton → neutron).
    list.push_back(UpgradeDef{
        "click_e", L"Electron Lens", L"+0.2 EPS",
        {{ResourceKind::Electron, "", 5}}, 1.5, UpgradeEffect::AutoEps, 0.2,
        0});

    list.push_back(UpgradeDef{
        "click_p", L"Proton Injector", L"+1 eV click power",
        {{ResourceKind::Proton, "", 5}}, 1.5, UpgradeEffect::ClickPower, 1.0,
        0});

    list.push_back(UpgradeDef{
        "click_n", L"Neutron Channel", L"+1% crit chance (max 100%)",
        {{ResourceKind::Neutron, "", 5}}, 1.5, UpgradeEffect::CritChance, 0.01,
        0});

    // Per element by Z: nucleus (click) -> atom (EPS) -> isotope coil.
    list.push_back(UpgradeDef{
        "nuc_Hydrogen", L"Hydrogen Core", L"+2 eV click power",
        {{ResourceKind::Nucleus, "Hydrogen", 5}}, 1.5, UpgradeEffect::ClickPower,
        2.0, 0});
    list.push_back(UpgradeDef{
        "atom_Hydrogen", L"Hydrogen Farm", L"+2.5 EPS",
        {{ResourceKind::Atom, "Hydrogen", 5}}, 1.5, UpgradeEffect::AutoEps, 2.5,
        0});
    // Coil bonuses by element order: H 0.10, then +0.10 each step.
    list.push_back(UpgradeDef{
        "annihilation_Hydrogen", L"H Annihilation Coil",
        L"+0.10 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Hydrogen", 3},
         {ResourceKind::Energy, "", 2000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 0.10, 0});

    list.push_back(UpgradeDef{
        "nuc_Helium", L"Helium Core", L"+10 eV click power",
        {{ResourceKind::Nucleus, "Helium", 5}}, 1.5, UpgradeEffect::ClickPower,
        10.0, 0});
    list.push_back(UpgradeDef{
        "atom_Helium", L"Helium Turbine", L"+5 EPS",
        {{ResourceKind::Atom, "Helium", 5}}, 1.5, UpgradeEffect::AutoEps, 5.0,
        0});
    list.push_back(UpgradeDef{
        "annihilation_Helium", L"He Annihilation Coil",
        L"+0.20 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Helium", 3},
         {ResourceKind::Energy, "", 5000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 0.20, 0});

    list.push_back(UpgradeDef{
        "nuc_Carbon", L"Carbon Core", L"+30 eV click power",
        {{ResourceKind::Nucleus, "Carbon", 5}}, 1.5, UpgradeEffect::ClickPower,
        30.0, 0});
    list.push_back(UpgradeDef{
        "atom_Carbon", L"Carbon Lattice", L"+15 EPS",
        {{ResourceKind::Atom, "Carbon", 5}}, 1.5, UpgradeEffect::AutoEps, 15.0,
        0});
    list.push_back(UpgradeDef{
        "annihilation_Carbon", L"C Annihilation Coil",
        L"+0.30 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Carbon", 3},
         {ResourceKind::Energy, "", 12000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 0.30, 0});

    list.push_back(UpgradeDef{
        "nuc_Oxygen", L"Oxygen Core", L"+50 eV click power",
        {{ResourceKind::Nucleus, "Oxygen", 5}}, 1.5, UpgradeEffect::ClickPower,
        50.0, 0});
    list.push_back(UpgradeDef{
        "atom_Oxygen", L"Oxygen Reactor", L"+30 EPS",
        {{ResourceKind::Atom, "Oxygen", 5}}, 1.5, UpgradeEffect::AutoEps, 30.0,
        0});
    list.push_back(UpgradeDef{
        "annihilation_Oxygen", L"O Annihilation Coil",
        L"+0.40 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Oxygen", 3},
         {ResourceKind::Energy, "", 20000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 0.40, 0});

    list.push_back(UpgradeDef{
        "nuc_Silicon", L"Silicon Core", L"+90 eV click power",
        {{ResourceKind::Nucleus, "Silicon", 5}}, 1.5, UpgradeEffect::ClickPower,
        90.0, 0});
    list.push_back(UpgradeDef{
        "atom_Silicon", L"Silicon Array", L"+60 EPS",
        {{ResourceKind::Atom, "Silicon", 5}}, 1.5, UpgradeEffect::AutoEps, 60.0,
        0});
    list.push_back(UpgradeDef{
        "annihilation_Silicon", L"Si Annihilation Coil",
        L"+0.50 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Silicon", 3},
         {ResourceKind::Energy, "", 40000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 0.50, 0});

    list.push_back(UpgradeDef{
        "nuc_Iron", L"Iron Core", L"+180 eV click power",
        {{ResourceKind::Nucleus, "Iron", 5}}, 1.5, UpgradeEffect::ClickPower,
        180.0, 0});
    list.push_back(UpgradeDef{
        "atom_Iron", L"Iron Forge", L"+120 EPS",
        {{ResourceKind::Atom, "Iron", 5}}, 1.5, UpgradeEffect::AutoEps, 120.0,
        0});
    list.push_back(UpgradeDef{
        "annihilation_Iron", L"Fe Annihilation Coil",
        L"+0.60 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Iron", 3},
         {ResourceKind::Energy, "", 80000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 0.60, 0});

    list.push_back(UpgradeDef{
        "nuc_Nickel", L"Nickel Core", L"+220 eV click power",
        {{ResourceKind::Nucleus, "Nickel", 5}}, 1.5, UpgradeEffect::ClickPower,
        220.0, 0});
    list.push_back(UpgradeDef{
        "atom_Nickel", L"Nickel Stack", L"+150 EPS",
        {{ResourceKind::Atom, "Nickel", 5}}, 1.5, UpgradeEffect::AutoEps, 150.0,
        0});
    list.push_back(UpgradeDef{
        "annihilation_Nickel", L"Ni Annihilation Coil",
        L"+0.70 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Nickel", 3},
         {ResourceKind::Energy, "", 100000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 0.70, 0});

    list.push_back(UpgradeDef{
        "nuc_Silver", L"Silver Core", L"+280 eV click power",
        {{ResourceKind::Nucleus, "Silver", 5}}, 1.5, UpgradeEffect::ClickPower,
        280.0, 0});
    list.push_back(UpgradeDef{
        "atom_Silver", L"Silver Circuit", L"+200 EPS",
        {{ResourceKind::Atom, "Silver", 5}}, 1.5, UpgradeEffect::AutoEps, 200.0,
        0});
    list.push_back(UpgradeDef{
        "annihilation_Silver", L"Ag Annihilation Coil",
        L"+0.80 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Silver", 3},
         {ResourceKind::Energy, "", 140000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 0.80, 0});

    list.push_back(UpgradeDef{
        "nuc_Xenon", L"Xenon Core", L"+340 eV click power",
        {{ResourceKind::Nucleus, "Xenon", 5}}, 1.5, UpgradeEffect::ClickPower,
        340.0, 0});
    list.push_back(UpgradeDef{
        "atom_Xenon", L"Xenon Chamber", L"+250 EPS",
        {{ResourceKind::Atom, "Xenon", 5}}, 1.5, UpgradeEffect::AutoEps, 250.0,
        0});
    list.push_back(UpgradeDef{
        "annihilation_Xenon", L"Xe Annihilation Coil",
        L"+0.90 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Xenon", 3},
         {ResourceKind::Energy, "", 170000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 0.90, 0});

    list.push_back(UpgradeDef{
        "nuc_Gold", L"Gold Core", L"+400 eV click power",
        {{ResourceKind::Nucleus, "Gold", 5}}, 1.5, UpgradeEffect::ClickPower,
        400.0, 0});
    list.push_back(UpgradeDef{
        "atom_Gold", L"Gold Dynamo", L"+300 EPS",
        {{ResourceKind::Atom, "Gold", 5}}, 1.5, UpgradeEffect::AutoEps, 300.0,
        0});
    list.push_back(UpgradeDef{
        "annihilation_Gold", L"Au Annihilation Coil",
        L"+1.00 isotope EPS multiplier",
        {{ResourceKind::Isotope, "Gold", 3},
         {ResourceKind::Energy, "", 200000}},
        1.6, UpgradeEffect::IsotopeEpsMult, 1.00, 0});

    // Special multi-cost upgrades last.
    list.push_back(UpgradeDef{
        "crit_amplifier", L"Critical Cascade", L"+1 crit multiplier",
        {{ResourceKind::Atom, "Hydrogen", 10},
         {ResourceKind::Atom, "Helium", 10},
         {ResourceKind::Atom, "Carbon", 10},
         {ResourceKind::Atom, "Oxygen", 10},
         {ResourceKind::Atom, "Silicon", 10},
         {ResourceKind::Atom, "Iron", 10}},
        1.9, UpgradeEffect::CritMultiplier, 1.0, 0});

    list.push_back(UpgradeDef{
        "quantum_cpu", L"Quantum Processor", L"+10 auto-click multiplier",
        {{ResourceKind::Electron, "", 10000},
         {ResourceKind::Nucleus, "Silicon", 500},
         {ResourceKind::Atom, "Gold", 50}},
        2.2, UpgradeEffect::AutoClickMult, 10.0, 0});

    return list;
  }

  void UnlockElementsForStar() {
    const int max_z = StarMaxAtomicNumber(star_type);
    for (auto& el : elements) {
      if (el.atomic_number <= max_z) {
        el.unlocked = true;
      }
    }
  }

  Element* FindElement(const std::string& id) {
    for (auto& el : elements) {
      if (el.id == id) {
        return &el;
      }
    }
    return nullptr;
  }

  const Element* FindElement(const std::string& id) const {
    for (const auto& el : elements) {
      if (el.id == id) {
        return &el;
      }
    }
    return nullptr;
  }

  // Mutation chance comes only from star dust prestige.
  double EffectiveMutationChance(const Element&) const {
    return std::clamp(star_dust * 0.001, 0.0, 0.95);
  }

  double ActivationEnergy(const Element& el) const {
    if (el.atomic_number <= kIronAtomicNumber) {
      return el.energy_activation;
    }
    const int over = el.atomic_number - kIronAtomicNumber;
    return el.energy_activation * std::pow(1.18, static_cast<double>(over));
  }

  // Heavier isotopes generate more passive energy (0.05 eV/s per Z).
  double IsotopeEpsPer(const Element& el) const {
    return 0.05 * static_cast<double>(el.atomic_number);
  }

  double ElementIsotopeEps(const Element& el) const {
    return el.isotope_count * IsotopeEpsPer(el) * isotope_eps_mult;
  }

  double IsotopeEps() const {
    double sum = 0.0;
    for (const auto& el : elements) {
      if (el.isotope_count > 0.0) {
        sum += el.isotope_count * IsotopeEpsPer(el);
      }
    }
    return sum * isotope_eps_mult;
  }

  double Eps() const {
    const double dust_mult = 1.0 + star_dust * 0.02;
    // Flat +Dust EPS is additive and is not scaled by the Dust EPS multiplier.
    return (auto_eps * auto_click_mult + IsotopeEps()) * dust_mult + star_dust;
  }

  void Tick(float dt) {
    if (dt > 0.f) {
      energy += Eps() * static_cast<double>(dt);
    }
  }

  ClickResult ClickStar() {
    std::uniform_real_distribution<double> dist(0.0, 1.0);
    ClickResult result;
    result.gain = click_power;
    if (dist(rng) < crit_chance) {
      result.gain *= crit_multiplier;
      result.crit = true;
    }
    energy += result.gain;
    return result;
  }

  bool MaterializeProton(double amount) {
    const double cost = amount * price_proton;
    if (amount <= 0.0 || energy < cost) {
      return false;
    }
    energy -= cost;
    protons += amount;
    return true;
  }

  bool MaterializeNeutron(double amount) {
    const double cost = amount * price_neutron;
    if (amount <= 0.0 || energy < cost) {
      return false;
    }
    energy -= cost;
    neutrons += amount;
    return true;
  }

  bool MaterializeElectron(double amount) {
    const double cost = amount * price_electron;
    if (amount <= 0.0 || energy < cost) {
      return false;
    }
    energy -= cost;
    electrons += amount;
    return true;
  }

  double MaxMaterialize(ResourceKind kind) const {
    double price = price_proton;
    if (kind == ResourceKind::Neutron) {
      price = price_neutron;
    } else if (kind == ResourceKind::Electron) {
      price = price_electron;
    }
    if (price <= 0.0) {
      return 0.0;
    }
    return std::floor(energy / price);
  }

  int ResolveBatchCount(int max_affordable, CraftBatch batch) const {
    if (max_affordable <= 0) {
      return 0;
    }
    const int mult = BatchMultiplier(batch);
    if (mult == 0) {
      return max_affordable;
    }
    return std::min(mult, max_affordable);
  }

  // Double path for particle Max buys (counts can exceed int32 ~2.1e9).
  double ResolveBatchAmount(double max_affordable, CraftBatch batch) const {
    if (!(max_affordable > 0.0)) {
      return 0.0;
    }
    const double capped = std::floor(max_affordable);
    const int mult = BatchMultiplier(batch);
    if (mult == 0) {
      return capped;
    }
    return std::min(static_cast<double>(mult), capped);
  }

  int ResolveCraftBatchCount(int max_affordable) const {
    return ResolveBatchCount(max_affordable, craft_batch);
  }

  double ResolveParticleBuyAmount(ResourceKind kind) const {
    return ResolveBatchAmount(MaxMaterialize(kind), buy_batch);
  }

  // Avoid UB/overflow when casting huge doubles to int.
  static int FloorToCount(double v) {
    if (!(v > 0.0) || !std::isfinite(v)) {
      return 0;
    }
    const double lim = static_cast<double>((std::numeric_limits<int>::max)());
    if (v >= lim) {
      return (std::numeric_limits<int>::max)();
    }
    return static_cast<int>(std::floor(v));
  }

  int MaxNucleusCraft(const Element& el) const {
    if (!el.unlocked || el.atomic_number > StarMaxAtomicNumber(star_type)) {
      return 0;
    }
    const double e_act = ActivationEnergy(el);
    if (el.protons_needed <= 0 || e_act <= 0.0) {
      return 0;
    }
    const double by_p = protons / el.protons_needed;
    const double by_n =
        el.neutrons_needed > 0 ? neutrons / el.neutrons_needed : by_p;
    const double by_e = energy / e_act;
    return FloorToCount(std::min({by_p, by_n, by_e}));
  }

  int MaxAtomCraft(const Element& el) const {
    if (!el.unlocked || el.atomic_number > StarMaxAtomicNumber(star_type)) {
      return 0;
    }
    if (el.electrons_needed <= 0) {
      return 0;
    }
    const double e_act = ActivationEnergy(el) * 0.35;
    if (e_act <= 0.0) {
      return 0;
    }
    const double by_nuc = el.nucleus_count;
    const double by_e = electrons / el.electrons_needed;
    const double by_energy = energy / e_act;
    return FloorToCount(std::min({by_nuc, by_e, by_energy}));
  }

  bool CraftNucleus(Element& el, int requested) {
    const int max_n = MaxNucleusCraft(el);
    const int count = ResolveCraftBatchCount(
        std::min(requested > 0 ? requested : max_n, max_n));
    if (count <= 0) {
      return false;
    }

    const double e_act = ActivationEnergy(el);
    const double spend_e = e_act * count;
    protons -= el.protons_needed * count;
    neutrons -= el.neutrons_needed * count;
    energy -= spend_e;

    el.nucleus_count += count;
    return true;
  }

  // Sample Binomial(n, p) without an O(n) Bernoulli loop.
  int SampleBinomial(int n, double p) {
    if (n <= 0 || p <= 0.0) {
      return 0;
    }
    if (p >= 1.0) {
      return n;
    }
    std::binomial_distribution<int> dist(n, p);
    return dist(rng);
  }

  bool CraftAtom(Element& el, int requested) {
    const int max_n = MaxAtomCraft(el);
    const int count = ResolveCraftBatchCount(
        std::min(requested > 0 ? requested : max_n, max_n));
    if (count <= 0) {
      return false;
    }

    const double e_act = ActivationEnergy(el) * 0.35;
    el.nucleus_count -= count;
    electrons -= el.electrons_needed * count;
    energy -= e_act * count;

    const double mut = EffectiveMutationChance(el);
    const int isotopes = SampleBinomial(count, mut);
    const int atoms = count - isotopes;
    el.atom_count += atoms;
    el.isotope_count += isotopes;
    if (isotopes > 0) {
      el.isotope_discovered = true;
    }
    return true;
  }

  bool IsotopeDiscovered(const std::string& element_id) const {
    const Element* el = FindElement(element_id);
    return el && el->isotope_discovered;
  }

  // Tech upgrades that spend an undiscovered isotope stay hidden.
  // Nucleus/atom upgrades appear only after the element is unlocked.
  bool IsUpgradeVisible(const UpgradeDef& up) const {
    for (const auto& c : up.base_costs) {
      if (c.kind == ResourceKind::Isotope && !IsotopeDiscovered(c.element_id)) {
        return false;
      }
      if ((c.kind == ResourceKind::Nucleus || c.kind == ResourceKind::Atom) &&
          !c.element_id.empty()) {
        const Element* el = FindElement(c.element_id);
        if (!el || !el->unlocked) {
          return false;
        }
      }
    }
    return true;
  }

  double ResourceAmount(const ResourceCost& cost) const {
    switch (cost.kind) {
      case ResourceKind::Energy:
        return energy;
      case ResourceKind::Proton:
        return protons;
      case ResourceKind::Neutron:
        return neutrons;
      case ResourceKind::Electron:
        return electrons;
      case ResourceKind::StarDust:
        return star_dust;
      case ResourceKind::Nucleus:
      case ResourceKind::Atom:
      case ResourceKind::Isotope: {
        const Element* el = FindElement(cost.element_id);
        if (!el) {
          return 0.0;
        }
        if (cost.kind == ResourceKind::Nucleus) {
          return el->nucleus_count;
        }
        if (cost.kind == ResourceKind::Atom) {
          return el->atom_count;
        }
        return el->isotope_count;
      }
    }
    return 0.0;
  }

  void SpendResource(const ResourceCost& cost, double amount) {
    switch (cost.kind) {
      case ResourceKind::Energy:
        energy -= amount;
        break;
      case ResourceKind::Proton:
        protons -= amount;
        break;
      case ResourceKind::Neutron:
        neutrons -= amount;
        break;
      case ResourceKind::Electron:
        electrons -= amount;
        break;
      case ResourceKind::StarDust:
        star_dust -= amount;
        break;
      case ResourceKind::Nucleus:
      case ResourceKind::Atom:
      case ResourceKind::Isotope: {
        Element* el = FindElement(cost.element_id);
        if (!el) {
          return;
        }
        if (cost.kind == ResourceKind::Nucleus) {
          el->nucleus_count -= amount;
        } else if (cost.kind == ResourceKind::Atom) {
          el->atom_count -= amount;
        } else {
          el->isotope_count -= amount;
        }
        break;
      }
    }
  }

  double ScaledCostAmount(const UpgradeDef& up, const ResourceCost& base) const {
    const double raw =
        base.amount * std::pow(up.cost_scale, static_cast<double>(up.level));
    return std::max(1.0, std::round(raw));
  }

  bool CanAffordUpgrade(const UpgradeDef& up) const {
    for (const auto& c : up.base_costs) {
      if (ResourceAmount(c) + 1e-9 < ScaledCostAmount(up, c)) {
        return false;
      }
    }
    return true;
  }

  bool BuyUpgrade(UpgradeDef& up) {
    if (!CanAffordUpgrade(up)) {
      return false;
    }
    for (const auto& c : up.base_costs) {
      SpendResource(c, ScaledCostAmount(up, c));
    }
    ++up.level;
    // Full recalc so grade thresholds apply correctly.
    RecalculateFromUpgrades();
    return true;
  }

  void ApplyUpgradeTotal(const UpgradeDef& up) {
    if (up.level <= 0) {
      return;
    }
    const double total = UpgradeScaledEffect(up);
    switch (up.effect) {
      case UpgradeEffect::ClickPower:
        // Accumulated into click_power as tech click strength X, then scaled by Dust.
        click_power += total;
        break;
      case UpgradeEffect::CritChance:
        crit_chance = std::min(1.0, crit_chance + total);
        break;
      case UpgradeEffect::CritMultiplier:
        crit_multiplier += total;
        break;
      case UpgradeEffect::AutoEps:
        auto_eps += total;
        break;
      case UpgradeEffect::AutoClickMult:
        auto_click_mult += total;
        break;
      case UpgradeEffect::IsotopeEpsMult:
        isotope_eps_mult += total;
        break;
    }
  }

  // Prestige-aware base stats, then re-apply all purchased upgrade levels.
  void RecalculateFromUpgrades() {
    // X starts at 0 and becomes click power from Tech ClickPower upgrades.
    click_power = 0.0;
    crit_chance = 0.0;
    crit_multiplier = 2.0;
    // Tech AutoEps only here; flat +Dust EPS is applied in Eps().
    auto_eps = 0.0;
    auto_click_mult = 1.0;
    isotope_eps_mult = 1.0;

    for (const auto& up : upgrades) {
      ApplyUpgradeTotal(up);
    }

    // Dust click bonus: X * Dust * 0.05 → total click = X * (1 + Dust * 0.05).
    // Innate base click of 1 is included in X so early game still works at Dust 0.
    const double X = 1.0 + click_power;
    click_power = X * (1.0 + star_dust * 0.05);
  }

  bool CanTriggerSupernova() const {
    // Require 100 atoms of the current star's cap element.
    const int max_z = StarMaxAtomicNumber(star_type);
    for (const auto& el : elements) {
      if (el.atomic_number == max_z && el.atom_count + 1e-9 >= kSupernovaAtomGoal) {
        return true;
      }
    }
    return false;
  }

  void SoftResetRun() {
    energy = 0.0;
    protons = 0.0;
    neutrons = 0.0;
    electrons = 0.0;

    for (auto& el : elements) {
      el.atom_count = 0.0;
      el.nucleus_count = 0.0;
      el.isotope_count = 0.0;
      // Isotope discoveries persist across soft resets.
    }

    for (auto& up : upgrades) {
      up.level = 0;
    }
  }

  bool TriggerSupernova() {
    if (star_type == StarType::NeutronStar || !CanTriggerSupernova()) {
      return false;
    }

    star_dust += StarDustReward(star_type);
    SoftResetRun();

    star_type = static_cast<StarType>(static_cast<int>(star_type) + 1);
    RecalculateFromUpgrades();
    UnlockElementsForStar();
    return true;
  }

  double PrestigeDustReward() const {
    if (star_type != StarType::NeutronStar) {
      return 0.0;
    }
    const Element* gold = FindElement("Gold");
    if (!gold) {
      return 0.0;
    }
    return std::floor(gold->atom_count / kPrestigeGoldPerDust);
  }

  bool CanTriggerPrestige() const {
    return PrestigeDustReward() + 1e-9 >= 1.0;
  }

  bool TriggerPrestige() {
    if (!CanTriggerPrestige()) {
      return false;
    }

    star_dust += PrestigeDustReward();
    SoftResetRun();
    // Neutron Star stays; unlocks already cover Gold.
    RecalculateFromUpgrades();
    UnlockElementsForStar();
    return true;
  }
};
